# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideMenuWithTabbar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SideMenuWithTabbar

  pod 'SideMenu', '~> 5.0'

  target 'SideMenuWithTabbarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SideMenuWithTabbarUITests' do
    # Pods for testing
  end

end
